# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewers:
  - reviewerA
  - reviewerB
  - reviewerC
  - reviewerD

# The number of reviewers added to the pull request
numberOfReviewers: 2

# A list of assignees, split into different groups, to be added to pull requests (GitHub user name)
assignees:
  - assigneeA

# The number of assignees to add from each group. Default is one.
numberOfAssignees: 0
